server:
  port: 10030
spring:
  application:
    name: MapleCoupon-settlement
  profiles:
    active: prod
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl