server:
  port: 10000
spring:
  application:
    name: fengCoupon-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
        enabled: false
      password: 51213002
    gateway:
      routes:
        - id: fengCoupon-merchant-admin
          uri: lb://fengCoupon-merchant-admin/api/merchant-admin/**
          predicates:
            - Path=/api/merchant-admin/**
        #          暂时先不加黑名单
        #          filters:
        #            - name: TokenValidate
        #              args:
        #                blackPathPre:
        #                  - /api/merchant-admin/coupon-task/create
        #                  - /api/merchant-admin/coupon-task/page
        - id: fengCoupon-engine
          uri: lb://fengCoupon-engine/api/engine/**
          predicates:
            - Path=/api/engine/**
        #          暂时先不加黑名单
        #          filters:
        #            - name: TokenValidate
        #              args:
        #                blackPathPre:
        #                  - /api/engine/coupon-template/redeem
        #                  - /api/engine/coupon-template-remind/create
        #                  - /api/engine/coupon-template-remind/list
        #                  - /api/engine/coupon-template-remind/cancel

        - id: fengCoupon-settlement
          uri: lb://fengCoupon-settlement/api/settlement/**
          predicates:
            - Path=/api/settlement/**

        - id: fengCoupon-distribution
          uri: lb://fengCoupon-distribution/api/distribution/**
          predicates:
            - Path=/api/distribution/**

        - id: fengCoupon-search
          uri: lb://fengCoupon-search/api/search/**
          predicates:
            - Path=/api/search/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}