server:
  port: 10000
spring:
  application:
    name: MapleCoupon-gateway
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: MapleCoupon-merchant-admin
          uri: lb://MapleCoupon-merchant-admin/api/merchant-admin/**
          predicates:
            - Path=/api/merchant-admin/**
#          黑名单
          filters:
            - name: TokenValidate
#              args:
#                blackPathPre:
#                  - /api/merchant-admin/coupon-task/create
#                  - /api/merchant-admin/coupon-task/page
        - id: MapleCoupon-engine
          uri: lb://MapleCoupon-engine/api/engine/**
          predicates:
            - Path=/api/engine/**
          filters:
            - name: TokenValidate
        - id: MapleCoupon-settlement
          uri: lb://MapleCoupon-settlement/api/settlement/**
          predicates:
            - Path=/api/settlement/**
          filters:
            - name: TokenValidate
        - id: MapleCoupon-distribution
          uri: lb://MapleCoupon-distribution/api/distribution/**
          predicates:
            - Path=/api/distribution/**
          filters:
            - name: TokenValidate
        - id: MapleCoupon-search
          uri: lb://MapleCoupon-search/api/search/**
          predicates:
            - Path=/api/search/**
          filters:
            - name: TokenValidate
        - id: MapleCoupon-auth
          uri: lb://MapleCoupon-auth/api/auth/**
          predicates:
            - Path=/api/auth/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/auth/user/register
                  - /api/auth/user/has-username
                  - /api/auth/user/login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}