server:
  port: 10000
spring:
  application:
    name: MapleCoupon-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
    gateway:
      routes:
        - id: MapleCoupon-merchant-admin
          uri: lb://MapleCoupon-merchant-admin/api/merchant-admin/**
          predicates:
            - Path=/api/merchant-admin/**
        #          暂时先不加黑名单
        #          filters:
        #            - name: TokenValidate
        #              args:
        #                blackPathPre:
        #                  - /api/merchant-admin/coupon-task/create
        #                  - /api/merchant-admin/coupon-task/page
        - id: MapleCoupon-engine
          uri: lb://MapleCoupon-engine/api/engine/**
          predicates:
            - Path=/api/engine/**
        #          暂时先不加黑名单
        #          filters:
        #            - name: TokenValidate
        #              args:
        #                blackPathPre:
        #                  - /api/engine/coupon-template/redeem
        #                  - /api/engine/coupon-template-remind/create
        #                  - /api/engine/coupon-template-remind/list
        #                  - /api/engine/coupon-template-remind/cancel

        - id: MapleCoupon-settlement
          uri: lb://MapleCoupon-settlement/api/settlement/**
          predicates:
            - Path=/api/settlement/**

        - id: MapleCoupon-distribution
          uri: lb://MapleCoupon-distribution/api/distribution/**
          predicates:
            - Path=/api/distribution/**

        - id: MapleCoupon-search
          uri: lb://MapleCoupon-search/api/search/**
          predicates:
            - Path=/api/search/**
        - id: MapleCoupon-auth
          uri: lb://MapleCoupon-auth/api/auth/**
          predicates:
            - Path=/api/auth/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}