server:
  port: 10010
spring:
  application:
    name: MapleCoupon-merchant-admin
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl-job:
  enabled: false
  access-token: default_token
  admin:
    addresses: http://localhost:8088/xxl-job-admin
  executor:
    application-name: fengCoupon-merchant-admin
    ip: 127.0.0.1
    log-retention-days: 30
    port: 19999

