server:
  port: 10020
spring:
  application:
    name: mapleCoupon-engine
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 39.105.15.60
      port: 6379
      password: xWBbAP7d2tSGdnES

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fengxin
knife4j:
  enable: true
  setting:
    language: zh_cn
rocketmq:
  name-server: 39.105.15.60:9876
  producer:
    group: mapleCoupon_engine-message-execute-producer
    send-message-timeout: 2000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数
one-coupon:
  user-coupon-list:
    save-cache:
      type: direct # 有两个选项：direct 在流程里直接操作，binlog 通过解析数据库日志后操作
