server:
  port: 10020
spring:
  application:
    name: MapleCoupon-engine
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848
  profiles:
    active: prod

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

one-coupon:
  user-coupon-list:
    save-cache:
      type: direct # 有两个选项：direct 在流程里直接操作，binlog 通过解析数据库日志后操作
  db-config:
    db-count: 2
