server:
  port: 10070
spring:
  application:
    name: MapleCoupon-auth
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848
  profiles:
    active: prod

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

one-coupon:
  db-config:
    db-count: 2
