server:
  port: 10070
spring:
  application:
    name: MapleCoupon-auth
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 39.105.15.60
      port: 6379
      password: xWBbAP7d2tSGdnES
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fengxin
knife4j:
  enable: true
  setting:
    language: zh_cn
one-coupon:
  db-config:
    db-count: 2
