# 数据源集合
dataSources:
  # 自定义数据源名称，可以是 ds_0 也可以叫 datasource_0 都可以
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://122.51.165.51:3306/one_coupon_0?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: xWfhdsajklfh
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://122.51.165.51:3306/one_coupon_1?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: xWfhdsajklfh

rules:
  - !SHARDING
    tables: # 需要分片的数据库表集合
      coupon_user: # 用户表
        # 真实存在数据库中的物理表
        actualDataNodes: ds_${0..1}.coupon_user_${0..15}
        databaseStrategy: # 分库策略
          standard: # 单分片键分库
            shardingColumn: username # 分片键
            shardingAlgorithmName: coupon_user_database_mod # 库分片算法名称，对应 rules[0].shardingAlgorithms
        tableStrategy: # 分表策略
          standard: # 单分片键分表
            shardingColumn: username # 分片键
            shardingAlgorithmName: coupon_user_table_mod # 表分片算法名称，对应 rules[0].shardingAlgorithms
    shardingAlgorithms: # 分片算法定义集合
      coupon_user_database_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: com.fengxin.maplecoupon.auth.dao.sharding.DBUserHashModShardingAlgorithm
          sharding-count: 16
          strategy: standard
      coupon_user_table_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: com.fengxin.maplecoupon.auth.dao.sharding.TableUserHashModShardingAlgorithm
          strategy: standard
props:
  # 配置 ShardingSphere 默认打印 SQL 执行语句
  sql-show: true