spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
  data:
    redis:
      host: 192.168.187.101
      port: 6379
      password: 51213002
      database: 1

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fengxin

knife4j:
  enable: true
  setting:
    language: zh_cn