server:
  port: 10040
spring:
  application:
    name: MapleCoupon-distribution
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
  profiles:
    active: prod

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
